import type { NextPage } from "next";
import Head from "next/head";
import { useEffect, useState } from "react";
import { getPokemon, getPokemonKando } from "./api/endpoints";

interface pokemon {
  name: string;
  url: string;
}
interface onePokemon {
  name: string;
  img: string;
}

const Home: NextPage = () => {
  const [listPokemon, setListPokemon] = useState([]);
  const [onePokemon, setOnePokemon] = useState<onePokemon>({
    name: "",
    img: "",
  });
  const [openPokemon, setOpenPokemon] = useState(false);
  // async function getPokemon() {
  //   return await getPokemonKando(0, 151);
  // }

  useEffect(() => {
    getPokemonKando(0, 151, setListPokemon);
  }, []);

  return (
    <div className="newC">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {!openPokemon &&
        listPokemon?.map((value: any) => (
          <div className="cardPokemon" key={value?.name}>
            <button
              onClick={() => {
                getPokemon(value?.name, setOnePokemon);
                setOpenPokemon(!openPokemon);
              }}
            >
              {value?.name}
            </button>
          </div>
        ))}

      {openPokemon && (
        <div className="cardPokemon">
          <img src={onePokemon?.img} alt="foto" />
          <p>{onePokemon?.name}</p>
          <button
            onClick={() => {
              setOpenPokemon(!openPokemon);
            }}
          >
            Voltar
          </button>
        </div>
      )}
    </div>
  );
};

export default Home;
